// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAraSkc2eVsC-bX3-l0zcshEyhB8shmVNg',
    appId: '1:241160369734:web:d8cad9fed702a5bab5bc47',
    messagingSenderId: '241160369734',
    projectId: 'waslapp-141c4',
    authDomain: 'waslapp-141c4.firebaseapp.com',
    storageBucket: 'waslapp-141c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2OYLmh30hjYzJMDdcKoztKeWXv7xSm5A',
    appId: '1:241160369734:android:f3191b08a7b929a3b5bc47',
    messagingSenderId: '241160369734',
    projectId: 'waslapp-141c4',
    storageBucket: 'waslapp-141c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbbTCs_P-bGXiOhizXwzSvWjU0sIwtcnA',
    appId: '1:241160369734:ios:1c1adc138cb56a5ab5bc47',
    messagingSenderId: '241160369734',
    projectId: 'waslapp-141c4',
    storageBucket: 'waslapp-141c4.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbbTCs_P-bGXiOhizXwzSvWjU0sIwtcnA',
    appId: '1:241160369734:ios:1c1adc138cb56a5ab5bc47',
    messagingSenderId: '241160369734',
    projectId: 'waslapp-141c4',
    storageBucket: 'waslapp-141c4.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAraSkc2eVsC-bX3-l0zcshEyhB8shmVNg',
    appId: '1:241160369734:web:0383fc554a667031b5bc47',
    messagingSenderId: '241160369734',
    projectId: 'waslapp-141c4',
    authDomain: 'waslapp-141c4.firebaseapp.com',
    storageBucket: 'waslapp-141c4.firebasestorage.app',
  );
}
